services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
  
  redis:
      image: docker.io/library/redis:7-alpine
      container_name: redis_cache
      restart: always
      env_file:
        - .env.redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data:Z

volumes:
  postgres_data:
  redis_data: